const forecast = JSON.stringify({
   "cod":"200",
   "message":0.0043,
   "cnt":39,
   "list":[
      {
         "dt":1536116400,
         "main":{
            "temp":66.52,
            "temp_min":66.52,
            "temp_max":69.56,
            "pressure":1006.56,
            "sea_level":1037.5,
            "grnd_level":1006.56,
            "humidity":89,
            "temp_kf":-1.69
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.01,
            "deg":166.503
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-05 03:00:00"
      },
      {
         "dt":1536127200,
         "main":{
            "temp":66.11,
            "temp_min":66.11,
            "temp_max":68.13,
            "pressure":1005.43,
            "sea_level":1036.46,
            "grnd_level":1005.43,
            "humidity":90,
            "temp_kf":-1.13
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.19,
            "deg":130.002
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-05 06:00:00"
      },
      {
         "dt":1536138000,
         "main":{
            "temp":66.34,
            "temp_min":66.34,
            "temp_max":67.36,
            "pressure":1004.92,
            "sea_level":1036.07,
            "grnd_level":1004.92,
            "humidity":89,
            "temp_kf":-0.56
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.42,
            "deg":127.006
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-05 09:00:00"
      },
      {
         "dt":1536148800,
         "main":{
            "temp":71.21,
            "temp_min":71.21,
            "temp_max":71.21,
            "pressure":1005.5,
            "sea_level":1036.44,
            "grnd_level":1005.5,
            "humidity":90,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.42,
            "deg":142.5
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-05 12:00:00"
      },
      {
         "dt":1536159600,
         "main":{
            "temp":82.53,
            "temp_min":82.53,
            "temp_max":82.53,
            "pressure":1005.52,
            "sea_level":1036.29,
            "grnd_level":1005.52,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.15,
            "deg":173.501
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-05 15:00:00"
      },
      {
         "dt":1536170400,
         "main":{
            "temp":88.5,
            "temp_min":88.5,
            "temp_max":88.5,
            "pressure":1003.89,
            "sea_level":1034.53,
            "grnd_level":1003.89,
            "humidity":61,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":5.21,
            "deg":227.005
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-05 18:00:00"
      },
      {
         "dt":1536181200,
         "main":{
            "temp":87.88,
            "temp_min":87.88,
            "temp_max":87.88,
            "pressure":1002.11,
            "sea_level":1032.74,
            "grnd_level":1002.11,
            "humidity":56,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":5.53,
            "deg":233.501
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-05 21:00:00"
      },
      {
         "dt":1536192000,
         "main":{
            "temp":78.28,
            "temp_min":78.28,
            "temp_max":78.28,
            "pressure":1002.06,
            "sea_level":1032.8,
            "grnd_level":1002.06,
            "humidity":73,
            "temp_kf":0
         },
         "weather":[
            {
               "id":501,
               "main":"Rain",
               "description":"moderate rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":12
         },
         "wind":{
            "speed":4.38,
            "deg":255.515
         },
         "rain":{
            "3h":3.595
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-06 00:00:00"
      },
      {
         "dt":1536202800,
         "main":{
            "temp":71.17,
            "temp_min":71.17,
            "temp_max":71.17,
            "pressure":1002.61,
            "sea_level":1033.32,
            "grnd_level":1002.61,
            "humidity":94,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.13,
            "deg":207.5
         },
         "rain":{
            "3h":2.515
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-06 03:00:00"
      },
      {
         "dt":1536213600,
         "main":{
            "temp":69.74,
            "temp_min":69.74,
            "temp_max":69.74,
            "pressure":1002.38,
            "sea_level":1033.12,
            "grnd_level":1002.38,
            "humidity":95,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":36
         },
         "wind":{
            "speed":2.62,
            "deg":287.501
         },
         "rain":{
            "3h":1.265
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-06 06:00:00"
      },
      {
         "dt":1536224400,
         "main":{
            "temp":68.47,
            "temp_min":68.47,
            "temp_max":68.47,
            "pressure":1002.24,
            "sea_level":1033.18,
            "grnd_level":1002.24,
            "humidity":95,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":20
         },
         "wind":{
            "speed":2.37,
            "deg":223.003
         },
         "rain":{
            "3h":0.0099999999999998
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-06 09:00:00"
      },
      {
         "dt":1536235200,
         "main":{
            "temp":70.45,
            "temp_min":70.45,
            "temp_max":70.45,
            "pressure":1002.87,
            "sea_level":1033.7,
            "grnd_level":1002.87,
            "humidity":97,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":76
         },
         "wind":{
            "speed":3.76,
            "deg":279
         },
         "rain":{
            "3h":0.305
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-06 12:00:00"
      },
      {
         "dt":1536246000,
         "main":{
            "temp":71.27,
            "temp_min":71.27,
            "temp_max":71.27,
            "pressure":1003.84,
            "sea_level":1034.7,
            "grnd_level":1003.84,
            "humidity":99,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.29,
            "deg":329.502
         },
         "rain":{
            "3h":2.03
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-06 15:00:00"
      },
      {
         "dt":1536256800,
         "main":{
            "temp":71.88,
            "temp_min":71.88,
            "temp_max":71.88,
            "pressure":1003.95,
            "sea_level":1034.9,
            "grnd_level":1003.95,
            "humidity":91,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":88
         },
         "wind":{
            "speed":3.94,
            "deg":341.505
         },
         "rain":{
            "3h":0.83
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-06 18:00:00"
      },
      {
         "dt":1536267600,
         "main":{
            "temp":73.18,
            "temp_min":73.18,
            "temp_max":73.18,
            "pressure":1004.06,
            "sea_level":1034.95,
            "grnd_level":1004.06,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":802,
               "main":"Clouds",
               "description":"scattered clouds",
               "icon":"03d"
            }
         ],
         "clouds":{
            "all":44
         },
         "wind":{
            "speed":4.41,
            "deg":350.004
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-06 21:00:00"
      },
      {
         "dt":1536278400,
         "main":{
            "temp":69.14,
            "temp_min":69.14,
            "temp_max":69.14,
            "pressure":1004.69,
            "sea_level":1035.77,
            "grnd_level":1004.69,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":68
         },
         "wind":{
            "speed":4.29,
            "deg":356.002
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-07 00:00:00"
      },
      {
         "dt":1536289200,
         "main":{
            "temp":65.93,
            "temp_min":65.93,
            "temp_max":65.93,
            "pressure":1005.54,
            "sea_level":1036.72,
            "grnd_level":1005.54,
            "humidity":80,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":4.38,
            "deg":19.013
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-07 03:00:00"
      },
      {
         "dt":1536300000,
         "main":{
            "temp":63.48,
            "temp_min":63.48,
            "temp_max":63.48,
            "pressure":1005.75,
            "sea_level":1037.02,
            "grnd_level":1005.75,
            "humidity":80,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":88
         },
         "wind":{
            "speed":3.49,
            "deg":28.5017
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-07 06:00:00"
      },
      {
         "dt":1536310800,
         "main":{
            "temp":61.88,
            "temp_min":61.88,
            "temp_max":61.88,
            "pressure":1005.49,
            "sea_level":1036.79,
            "grnd_level":1005.49,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":2.37,
            "deg":10.5025
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-07 09:00:00"
      },
      {
         "dt":1536321600,
         "main":{
            "temp":61.63,
            "temp_min":61.63,
            "temp_max":61.63,
            "pressure":1005.9,
            "sea_level":1037.29,
            "grnd_level":1005.9,
            "humidity":85,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.04,
            "deg":19.502
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-07 12:00:00"
      },
      {
         "dt":1536332400,
         "main":{
            "temp":64.05,
            "temp_min":64.05,
            "temp_max":64.05,
            "pressure":1006.23,
            "sea_level":1037.42,
            "grnd_level":1006.23,
            "humidity":86,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":3.15,
            "deg":49.0031
         },
         "rain":{
            "3h":0.025
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-07 15:00:00"
      },
      {
         "dt":1536343200,
         "main":{
            "temp":67.53,
            "temp_min":67.53,
            "temp_max":67.53,
            "pressure":1005.5,
            "sea_level":1036.56,
            "grnd_level":1005.5,
            "humidity":83,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":76
         },
         "wind":{
            "speed":3.24,
            "deg":43.005
         },
         "rain":{
            "3h":0.0099999999999998
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-07 18:00:00"
      },
      {
         "dt":1536354000,
         "main":{
            "temp":69.04,
            "temp_min":69.04,
            "temp_max":69.04,
            "pressure":1004.36,
            "sea_level":1035.44,
            "grnd_level":1004.36,
            "humidity":79,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":2.91,
            "deg":4.00201
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-07 21:00:00"
      },
      {
         "dt":1536364800,
         "main":{
            "temp":66.89,
            "temp_min":66.89,
            "temp_max":66.89,
            "pressure":1004.44,
            "sea_level":1035.66,
            "grnd_level":1004.44,
            "humidity":81,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":2.62,
            "deg":6.50409
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-08 00:00:00"
      },
      {
         "dt":1536375600,
         "main":{
            "temp":65.04,
            "temp_min":65.04,
            "temp_max":65.04,
            "pressure":1004.63,
            "sea_level":1035.86,
            "grnd_level":1004.63,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":3.76,
            "deg":34.5016
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-08 03:00:00"
      },
      {
         "dt":1536386400,
         "main":{
            "temp":63.33,
            "temp_min":63.33,
            "temp_max":63.33,
            "pressure":1004.12,
            "sea_level":1035.5,
            "grnd_level":1004.12,
            "humidity":78,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":3.83,
            "deg":54.5053
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-08 06:00:00"
      },
      {
         "dt":1536397200,
         "main":{
            "temp":61.58,
            "temp_min":61.58,
            "temp_max":61.58,
            "pressure":1004.44,
            "sea_level":1035.7,
            "grnd_level":1004.44,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":4.72,
            "deg":72.5065
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-08 09:00:00"
      },
      {
         "dt":1536408000,
         "main":{
            "temp":59.74,
            "temp_min":59.74,
            "temp_max":59.74,
            "pressure":1004.9,
            "sea_level":1036.27,
            "grnd_level":1004.9,
            "humidity":70,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":5.17,
            "deg":69.5008
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-08 12:00:00"
      },
      {
         "dt":1536418800,
         "main":{
            "temp":62.28,
            "temp_min":62.28,
            "temp_max":62.28,
            "pressure":1005.77,
            "sea_level":1037.06,
            "grnd_level":1005.77,
            "humidity":67,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":88
         },
         "wind":{
            "speed":4.92,
            "deg":73.0001
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-08 15:00:00"
      },
      {
         "dt":1536429600,
         "main":{
            "temp":66.27,
            "temp_min":66.27,
            "temp_max":66.27,
            "pressure":1005.51,
            "sea_level":1036.65,
            "grnd_level":1005.51,
            "humidity":63,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":80
         },
         "wind":{
            "speed":4.52,
            "deg":83.0005
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-08 18:00:00"
      },
      {
         "dt":1536440400,
         "main":{
            "temp":65.45,
            "temp_min":65.45,
            "temp_max":65.45,
            "pressure":1005.03,
            "sea_level":1036.16,
            "grnd_level":1005.03,
            "humidity":67,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":4.63,
            "deg":102.503
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-08 21:00:00"
      },
      {
         "dt":1536451200,
         "main":{
            "temp":62.65,
            "temp_min":62.65,
            "temp_max":62.65,
            "pressure":1005.63,
            "sea_level":1036.82,
            "grnd_level":1005.63,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":4.97,
            "deg":109.002
         },
         "rain":{
            "3h":0.010000000000002
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-09 00:00:00"
      },
      {
         "dt":1536462000,
         "main":{
            "temp":61.11,
            "temp_min":61.11,
            "temp_max":61.11,
            "pressure":1006.19,
            "sea_level":1037.55,
            "grnd_level":1006.19,
            "humidity":70,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":5.35,
            "deg":114.505
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-09 03:00:00"
      },
      {
         "dt":1536472800,
         "main":{
            "temp":59.4,
            "temp_min":59.4,
            "temp_max":59.4,
            "pressure":1006.17,
            "sea_level":1037.55,
            "grnd_level":1006.17,
            "humidity":71,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":4.9,
            "deg":120.002
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-09 06:00:00"
      },
      {
         "dt":1536483600,
         "main":{
            "temp":57.77,
            "temp_min":57.77,
            "temp_max":57.77,
            "pressure":1005.72,
            "sea_level":1037.18,
            "grnd_level":1005.72,
            "humidity":74,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04n"
            }
         ],
         "clouds":{
            "all":88
         },
         "wind":{
            "speed":4.85,
            "deg":111.002
         },
         "rain":{

         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-09-09 09:00:00"
      },
      {
         "dt":1536494400,
         "main":{
            "temp":57.54,
            "temp_min":57.54,
            "temp_max":57.54,
            "pressure":1006.07,
            "sea_level":1037.53,
            "grnd_level":1006.07,
            "humidity":77,
            "temp_kf":0
         },
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":76
         },
         "wind":{
            "speed":5.97,
            "deg":109.505
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-09 12:00:00"
      },
      {
         "dt":1536505200,
         "main":{
            "temp":60.95,
            "temp_min":60.95,
            "temp_max":60.95,
            "pressure":1006.39,
            "sea_level":1037.69,
            "grnd_level":1006.39,
            "humidity":66,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":88
         },
         "wind":{
            "speed":7.52,
            "deg":121.001
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-09 15:00:00"
      },
      {
         "dt":1536516000,
         "main":{
            "temp":62.44,
            "temp_min":62.44,
            "temp_max":62.44,
            "pressure":1005.71,
            "sea_level":1036.97,
            "grnd_level":1005.71,
            "humidity":61,
            "temp_kf":0
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "clouds":{
            "all":92
         },
         "wind":{
            "speed":7.07,
            "deg":123.502
         },
         "rain":{

         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-09 18:00:00"
      },
      {
         "dt":1536526800,
         "main":{
            "temp":60.16,
            "temp_min":60.16,
            "temp_max":60.16,
            "pressure":1004.91,
            "sea_level":1036.2,
            "grnd_level":1004.91,
            "humidity":66,
            "temp_kf":0
         },
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":{
            "all":100
         },
         "wind":{
            "speed":6.98,
            "deg":126.004
         },
         "rain":{
            "3h":0.22
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-09-09 21:00:00"
      }
   ],
   "city":{
      "id":5128638,
      "name":"New York",
      "coord":{
         "lat":43.0004,
         "lon":-75.5
      },
      "country":"US"
   }
})

export default forecast